### PR TITLE
cleanup: instruct users to refer to new example

### PR DESCRIPTION
**Pull request by stephanwlee**
We now have better and more up-to-date example in the TensorBoard repo.
This allows TensorBoard maintainers to not forget about the example and
make the document stale.

### CODE REVIEW

**Review by nfelt — APPROVED** [review]
LGTM, but should we also delete the actual code?  It can always be retrieved from history, and then it makes it completely clear that it's no longer intended for use.

**Comment by stephanwlee** [comment]
Other Polymer/Angular projects seem to just archive the repo (e.g., https://github.com/ngrx/example-app#this-repository-is-for-version-2x-of-the-example-application) 

Should I just call out that this is TensorBoard <=1.13 style?

**Comment by nfelt** [comment]
I guess that's fine then.  Sure, we can call that out and leave it up as a reference for people using old versions of TensorBoard.

Also I notice the ngrx example has been converted to a read-only repo, which could be a good idea too.

**Comment by stephanwlee** [comment]
Yup, read-only after the PR lands :)

**Pull request merged**
